### ISSUE TITLE
Build detail view for resource

### ISSUE THREAD

**Issue by dstrukt** [ln-pay/bitcoinersbest#31]

**Comment by tkijewski** [comment]
is this technically done now?

**Comment by dstrukt** [comment]
no -- i just made it a backlog item because we shelved the idea until we realize a need for it

**Comment by tkijewski** [comment]
Accessible here:

http://bitcoinersbest.local:9111/content/view?id=<ResItem ID>

http://bitcoinersbest.local:9111/content/view?id=50

`views/content/view.php` is view file
