### ISSUE TITLE
[Vote] Prompt login/sign modal on vote if not logged in

### ISSUE THREAD

**Issue by dstrukt** [ln-pay/bitcoinersbest#33]

**Comment by tkijewski** [comment]
Should be able to call the modal when needed with this jQuery.

```
    $('#contentCreated').modal({
          keyboard: false
        });
```
Assuming you are talking about this modal:

<img width="942" alt="Login 2019-11-13 12-35-54" src="https://user-images.githubusercontent.com/3043754/68764191-25b4b800-0612-11ea-9d67-d3dd79fc5c7c.png">
