### ISSUE TITLE
[Bug] Random "}" is appearing above the list view

### ISSUE THREAD

**Issue by dstrukt** [ln-pay/bitcoinersbest#46]
<img width="1509" alt="Screen Shot 2019-11-10 at 2 36 42 AM" src="https://user-images.githubusercontent.com/6250771/68542585-0f350500-0363-11ea-9a96-09a5c0da4789.png">

**Comment by tkijewski** [comment]
I don't see this

**Comment by dstrukt** [comment]
i fixed it -- was just a stray }
